{{- if or .Values.secrets.apiKey .Values.secrets.accessKey .Values.secrets.adminKey .Values.secrets.vncPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "camofox.fullname" . }}
  labels:
    {{- include "camofox.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.apiKey }}
  CAMOFOX_API_KEY: {{ .Values.secrets.apiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.accessKey }}
  CAMOFOX_ACCESS_KEY: {{ .Values.secrets.accessKey | quote }}
  {{- end }}
  {{- if .Values.secrets.adminKey }}
  CAMOFOX_ADMIN_KEY: {{ .Values.secrets.adminKey | quote }}
  {{- end }}
  {{- if .Values.secrets.vncPassword }}
  VNC_PASSWORD: {{ .Values.secrets.vncPassword | quote }}
  {{- end }}
{{- end }}
