apiVersion: v1
kind: Service
metadata:
  name: {{ include "camofox.fullname" . }}
  labels:
    {{- include "camofox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "camofox.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
    {{- if .Values.vnc.enabled }}
    - name: vnc
      port: {{ .Values.service.vncPort }}
      targetPort: vnc
      protocol: TCP
    {{- end }}
